quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=catalogsvc
quarkus.datasource.password=r3dh4t1!
quarkus.datasource.reactive.url=postgresql://localhost:5432/catalog

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.http.port=8080
