quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive=true
quarkus.datasource.username=${POSTGRESQL_USERNAME:catalogsvc}
quarkus.datasource.password=${POSTGRESQL_PASSWORD:r3dh4t1!}
quarkus.datasource.reactive.url=${POSTGRESQL_URL:postgresql://${POSTGRESQL_HOST:localhost}:5432/catalog}
quarkus.datasource.devservices.enabled=false

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.http.port=${QUARKUS_HTTP_PORT:8080}
